[package]
name = "musket"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/isfegu/musket"
description = "Musket is a command line interface to send a URL to several destinations."
license = "MIT"
authors = ["isfegu"]
readme = "README.md"
homepage = "https://github.com/isfegu/musket"
keywords = ["ssmm", "cli", "bookmarks"]
categories = ["command-line-utilities"]

[[bin]]
name = "musket"
path = "src/bin.rs"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.21", features = ["derive"] }
confy = "0.6.1"
libsql = "0.6.0"
serde = "1.0.215"
tokio = "1.41.1"